// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaNomina.Data;

#nullable disable

namespace SistemaNomina.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260302215401_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SistemaNomina.Models.Departments", b =>
                {
                    b.Property<int>("DeptNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("dept_no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeptNo"));

                    b.Property<string>("DeptName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dept_name");

                    b.HasKey("DeptNo")
                        .HasName("pk_departments");

                    b.ToTable("departments", (string)null);
                });

            modelBuilder.Entity("SistemaNomina.Models.DeptEmp", b =>
                {
                    b.Property<int>("EmpNo")
                        .HasColumnType("int")
                        .HasColumnName("emp_no");

                    b.Property<int>("DeptNo")
                        .HasColumnType("int")
                        .HasColumnName("dept_no");

                    b.Property<string>("FromDate")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("from_date");

                    b.Property<string>("ToDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("to_date");

                    b.HasKey("EmpNo", "DeptNo", "FromDate")
                        .HasName("pk_dept_emp");

                    b.HasIndex("DeptNo")
                        .HasDatabaseName("ix_dept_emp_dept_no");

                    b.ToTable("dept_emp", (string)null);
                });

            modelBuilder.Entity("SistemaNomina.Models.DeptManager", b =>
                {
                    b.Property<int>("EmpNo")
                        .HasColumnType("int")
                        .HasColumnName("emp_no");

                    b.Property<int>("DeptNo")
                        .HasColumnType("int")
                        .HasColumnName("dept_no");

                    b.Property<string>("FromDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("from_date");

                    b.Property<string>("ToDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("to_date");

                    b.HasKey("EmpNo")
                        .HasName("pk_dept_manager");

                    b.HasIndex("DeptNo")
                        .HasDatabaseName("ix_dept_manager_dept_no");

                    b.ToTable("dept_manager", (string)null);
                });

            modelBuilder.Entity("SistemaNomina.Models.Employees", b =>
                {
                    b.Property<int>("EmpNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("emp_no");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpNo"));

                    b.Property<string>("BirthDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("birth_date");

                    b.Property<string>("Ci")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ci");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("correo");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)")
                        .HasColumnName("gender");

                    b.Property<string>("HireDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hire_date");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.HasKey("EmpNo")
                        .HasName("pk_employees");

                    b.ToTable("employees", (string)null);
                });

            modelBuilder.Entity("SistemaNomina.Models.LogAuditoriaSalarios", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DetalleCambio")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detalle_cambio");

                    b.Property<int>("EmpNo")
                        .HasColumnType("int")
                        .HasColumnName("emp_no");

                    b.Property<string>("FechaActualizacion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fecha_actualizacion");

                    b.Property<long>("Salario")
                        .HasColumnType("bigint")
                        .HasColumnName("salario");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usuario");

                    b.HasKey("Id")
                        .HasName("pk_log_auditoria_salarios");

                    b.HasIndex("EmpNo")
                        .HasDatabaseName("ix_log_auditoria_salarios_emp_no");

                    b.ToTable("log_auditoria_salarios", (string)null);
                });

            modelBuilder.Entity("SistemaNomina.Models.Salaries", b =>
                {
                    b.Property<int>("EmpNo")
                        .HasColumnType("int")
                        .HasColumnName("emp_no");

                    b.Property<string>("FromDate")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("from_date");

                    b.Property<long>("Salary")
                        .HasColumnType("bigint")
                        .HasColumnName("salary");

                    b.Property<string>("ToDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("to_date");

                    b.HasKey("EmpNo", "FromDate")
                        .HasName("pk_salaries");

                    b.ToTable("salaries", (string)null);
                });

            modelBuilder.Entity("SistemaNomina.Models.Titles", b =>
                {
                    b.Property<int>("EmpNo")
                        .HasColumnType("int")
                        .HasColumnName("emp_no");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("title");

                    b.Property<string>("FromDate")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("from_date");

                    b.Property<string>("ToDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("to_date");

                    b.HasKey("EmpNo", "Title", "FromDate")
                        .HasName("pk_titles");

                    b.ToTable("titles", (string)null);
                });

            modelBuilder.Entity("SistemaNomina.Models.Users", b =>
                {
                    b.Property<int>("EmpNo")
                        .HasColumnType("int")
                        .HasColumnName("emp_no");

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("clave");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("usuario");

                    b.HasKey("EmpNo")
                        .HasName("pk_users");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SistemaNomina.Models.DeptEmp", b =>
                {
                    b.HasOne("SistemaNomina.Models.Departments", "Departments")
                        .WithMany("DeptEmps")
                        .HasForeignKey("DeptNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dept_emp_departments_dept_no");

                    b.HasOne("SistemaNomina.Models.Employees", "Employees")
                        .WithMany("DeptEmps")
                        .HasForeignKey("EmpNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dept_emp_employees_emp_no");

                    b.Navigation("Departments");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("SistemaNomina.Models.DeptManager", b =>
                {
                    b.HasOne("SistemaNomina.Models.Departments", "Departments")
                        .WithMany("DeptManagers")
                        .HasForeignKey("DeptNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dept_manager_departments_dept_no");

                    b.HasOne("SistemaNomina.Models.Employees", "Employees")
                        .WithMany("DeptManagers")
                        .HasForeignKey("EmpNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_dept_manager_employees_emp_no");

                    b.Navigation("Departments");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("SistemaNomina.Models.LogAuditoriaSalarios", b =>
                {
                    b.HasOne("SistemaNomina.Models.Employees", "Employees")
                        .WithMany("LogAuditoriaSalarios")
                        .HasForeignKey("EmpNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_log_auditoria_salarios_employees_emp_no");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("SistemaNomina.Models.Salaries", b =>
                {
                    b.HasOne("SistemaNomina.Models.Employees", "Employees")
                        .WithMany("Salaries")
                        .HasForeignKey("EmpNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_salaries_employees_emp_no");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("SistemaNomina.Models.Titles", b =>
                {
                    b.HasOne("SistemaNomina.Models.Employees", "Employees")
                        .WithMany("Titles")
                        .HasForeignKey("EmpNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_titles_employees_emp_no");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("SistemaNomina.Models.Users", b =>
                {
                    b.HasOne("SistemaNomina.Models.Employees", "Employees")
                        .WithOne("Users")
                        .HasForeignKey("SistemaNomina.Models.Users", "EmpNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_users_employees_emp_no");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("SistemaNomina.Models.Departments", b =>
                {
                    b.Navigation("DeptEmps");

                    b.Navigation("DeptManagers");
                });

            modelBuilder.Entity("SistemaNomina.Models.Employees", b =>
                {
                    b.Navigation("DeptEmps");

                    b.Navigation("DeptManagers");

                    b.Navigation("LogAuditoriaSalarios");

                    b.Navigation("Salaries");

                    b.Navigation("Titles");

                    b.Navigation("Users")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
